# Generated by Django 5.2.7 on 2026-03-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('discount', models.IntegerField()),
                ('discrption', models.TextField()),
                ('stockavb', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='products_img')),
            ],
        ),
    ]
