# Generated by Django 5.2.7 on 2025-12-31 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zepto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='franchise',
            name='logo_url',
            field=models.ImageField(blank=True, null=True, upload_to='franchise_logos/'),
        ),
    ]
