# Generated by Django 5.2.7 on 2026-01-03 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zepto', '0002_alter_franchise_logo_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('age', models.PositiveBigIntegerField()),
                ('role', models.CharField(choices=[('Batsman', 'Batsman'), ('Bowler', 'Bowler'), ('All_Rounder', 'All_Rounder'), ('Wicket_Keeper', 'Wicket_keeper')], max_length=40)),
                ('nationality', models.CharField(max_length=60)),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zepto.franchise')),
            ],
        ),
    ]
