# Generated by Django 5.2.7 on 2026-01-06 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zepto', '0003_players'),
    ]

    operations = [
        migrations.CreateModel(
            name='stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=150)),
                ('capicity', models.PositiveBigIntegerField()),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zepto.franchise')),
            ],
        ),
    ]
