# Generated by Django 5.2.7 on 2026-03-11 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zepto', '0005_profilepic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilepic',
            old_name='profile_pic',
            new_name='profile_picture',
        ),
    ]
